a=int(input("first number: "))
b=int(input("second number: "))
print("the value of ", a ,"+",b, "is:" ,a+b)
print("the value of ", a ,"-",b, "is:" ,a-b)
print("the value of ", a ,"*",b, "is:" ,a*b)
print("the value of ", a ,"/",b, "is:" ,a/b)
print("the value of",a,"//",b,"is:",a//b)