a=input("enter your name:   ")
print("hi", a,"welcome to harshal nikam's code")
b=input("enter your birth year:   ")
print("you are", 2026-int(b),"years old")
len1=len(a)
print("your name has",len1,"characters")
c=int(input())
d=int(input())
print(a[c:d])